name: Generate static page & Deploy to Firebase Hosting

on:
  repository_dispatch:
    types: [update_post]
  push:
    branches:
      - master

jobs:

  generate-deploy:
    name: GENERATE and DEPLOY
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn

      - name: Generate static page
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
          MICRO_CMS_API_URL: ${{ secrets.MICRO_CMS_API_URL }}
        run: yarn generate

      - name: Deploy to Firebase Hosting
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}